// Generates dist/sitemap.xml after `vite build`. Runs in plain Node (not through Vite/tsc),
// so story/bulletin slugs are pulled out of the source files with a regex instead of importing
// the TS modules directly.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";

const rootDir = path.dirname(fileURLToPath(import.meta.url)) + "/..";
const SITE_URL = "https://imvishi.com";

function extractSlugs(filePath) {
  const source = readFileSync(path.join(rootDir, filePath), "utf-8");
  return [...source.matchAll(/slug:\s*"([^"]+)"/g)].map((m) => m[1]);
}

const storySlugs = extractSlugs("src/data/stories.ts");
const bulletinSlugs = extractSlugs("src/data/bulletins.ts");

const staticRoutes = [{ loc: "/", priority: "1.0" }];
const storyRoutes = storySlugs.map((slug) => ({ loc: `/story/${slug}`, priority: "0.8" }));
const bulletinRoutes = bulletinSlugs.map((slug) => ({ loc: `/update/${slug}`, priority: "0.5" }));

const routes = [...staticRoutes, ...storyRoutes, ...bulletinRoutes];

const today = new Date().toISOString().slice(0, 10);

const body = routes
  .map(
    ({ loc, priority }) => `  <url>
    <loc>${SITE_URL}${loc}</loc>
    <lastmod>${today}</lastmod>
    <priority>${priority}</priority>
  </url>`
  )
  .join("\n");

const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/generate-sitemap.mjs at build time. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${body}
</urlset>
`;

writeFileSync(path.join(rootDir, "dist/sitemap.xml"), xml);
console.log(`sitemap.xml written with ${routes.length} routes`);
